import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class AIPromptService extends ChangeNotifier {
  static const String _apiKey = '';
  static const String _apiUrl =
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent';

  String? _originalPhotoPath;
  String? _generatedImagePath;
  bool _isGenerating = false;
  String? _errorMessage;

  // Getters
  String? get originalPhotoPath => _originalPhotoPath;
  String? get generatedImagePath => _generatedImagePath;
  bool get isGenerating => _isGenerating;
  String? get errorMessage => _errorMessage;
  bool get hasGeneratedImage => _generatedImagePath != null;

  void setOriginalPhoto(String path) {
    _originalPhotoPath = path;
    _generatedImagePath = null;
    _errorMessage = null;
    notifyListeners();
  }

  /// Generate AI image from prompt using Gemini 3 Flash Image
  Future<void> generateAIImage(String prompt) async {
    _isGenerating = true;
    _errorMessage = null;
    notifyListeners();

    try {
      final Map<String, dynamic> requestBody = {
        "contents": [
          {
            "parts": [
              {"text": prompt},
            ],
          },
        ],
        "generationConfig": {
          "response_modalities": ["IMAGE"],
        },
      };

      final response = await http
          .post(
            Uri.parse('$_apiUrl?key=$_apiKey'),
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode(requestBody),
          )
          .timeout(const Duration(seconds: 90));

      if (response.statusCode == 200) {
        final Map<String, dynamic> data = jsonDecode(response.body);

        // Extract base64 string from nested response structure
        final String? base64Data = data['candidates']?[0]['content']?['parts']
            ?.firstWhere(
              (p) => p.containsKey('inline_data'),
              orElse: () => null,
            )?['inline_data']['data'];

        if (base64Data != null) {
          final Uint8List imageBytes = base64Decode(base64Data);

          // Save the generated bytes to a temporary local file
          final String tempPath = Directory.systemTemp.path;
          final String fileName =
              'nano_banana_${DateTime.now().millisecondsSinceEpoch}.png';
          final File outputFile = File('$tempPath/$fileName');
          await outputFile.writeAsBytes(imageBytes);

          _generatedImagePath = outputFile.path;
        } else {
          _errorMessage = 'No image data returned from API.';
        }
      } else {
        _errorMessage = 'API Error: ${response.statusCode} - ${response.body}';
      }
    } catch (e) {
      _errorMessage = 'Error generating image: $e';
    } finally {
      _isGenerating = false;
      notifyListeners();
    }
  }

  void clearGeneratedImage() {
    _generatedImagePath = null;
    _errorMessage = null;
    notifyListeners();
  }

  void reset() {
    _originalPhotoPath = null;
    _generatedImagePath = null;
    _isGenerating = false;
    _errorMessage = null;
    notifyListeners();
  }
}
